### ISSUE TITLE
POST_NPC_UPDATE_FILTER fires multiple times per NPC update

### ISSUE THREAD

**Issue by Syntax-Sculptor** [Team-Compliance/libraryofisaac#17]
POST_NPC_UPDATE_FILTER should only fire once per NPC update. However, this callback is firing multiple times per update.

**Comment by Syntax-Sculptor** [comment]
This seems to be tied to luamod.

**Comment by thicco-catto** [comment]
I've tried the following code and i can't reproduce the bug, could you provide more details or a reprex that causes the bug?
```lua
TestingMod = RegisterMod("Testing Mod", 1)

local t = require("library_of_isaac.TSIL")
t.Init("library_of_isaac")

TestingMod:AddCallback(TSIL.Enums.CustomCallback.POST_NPC_UPDATE_FILTER, function (_, npc)
	print(Game():GetFrameCount(), npc.FrameCount)
end)
```
![image](https://github.com/Team-Compliance/libraryofisaac/assets/67873211/0e439517-9d85-46fd-aa92-5303c83206ca)

**Comment by Syntax-Sculptor** [comment]
Turns out it was just a bizarre mod conflict. Though I had all other mods disabled during testing, whoops 😓
